### ISSUE TITLE
STM32G070 can not use delay(), even before the timer Init?

### ISSUE THREAD

**Issue by ghost** [khoih-prog/STM32_TimerInterrupt#7] opened 2022-04-08 07:49 UTC
Here is my code

```
/*----------------- STM32Timer -----------------*/
STM32Timer freeRTOSTimer(TIM1);
const uint32_t FREERTOS_TIMER_PERIOD = 500;	// Unit
```

then I use the delay in the setup funtcion ,

```
pinMode(LEDR, 	OUTPUT);
pinMode(LEDB, 	OUTPUT);

analogReadResolution(12);				

Serial.begin(9600);
delay(1);			// Wait stable
if (freeRTOSTimer.attachInterruptInterval(FREERTOS_TIMER_PERIOD, freeRTOSTimerHandle))
{
    Serial.printf("Starting  freeRTOSTimer OK, millis() = %d", millis());
}
else
{
    Serial.println("Can't set freeRTOSTimer. Select another freq. or timer");
}

```

but my program was dead in the delay(1), then I debug it, I found that getCurrentMills() always be 0. as the picture
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/55439370/162390123-43c93239-3c20-4ae8-bbfc-6652d67fba3f.png">
  
But the same program I can use in the stm32l476RG.

Could you help me?

**Comment by khoih-prog** [comment] 2022-04-08 15:01
This issue is not related to this library because it happens in the core's functions `delay()` **before** calling the TimerInterrupt.

Why not just remove the delay(), or simplify the code to isolate the issue ?

I also don't have that special board to help you and suggest you post the issue in [**STM32 Forum**](https://www.stm32duino.com/viewforum.php?f=62) to ask for help. Be sure to post the [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example) or your post will be ignored.

I'm closing the issue now and only reopen when you prove this is a bug of the library. 

Good Luck,

**Closed as completed by khoih-prog** 2022-04-08 15:01 UTC
